thesis > result1.txt
thesis > result2.txt
thesis > result3.txt
thesis > result4.txt
thesis > result5.txt
thesis > result6.txt
thesis > result7.txt
thesis > result8.txt
thesis > result9.txt
thesis > result10.txt
thesis > result11.txt
thesis > result12.txt
thesis > result13.txt
thesis > result14.txt
thesis > result15.txt