thesiscomp > Cresults16.txt
thesiscomp > Cresults17.txt
thesiscomp > Cresults18.txt
thesiscomp > Cresults19.txt
thesiscomp > Cresults20.txt
thesiscomp > Cresults21.txt
thesiscomp > Cresults22.txt
thesiscomp > Cresults23.txt
thesiscomp > Cresults24.txt
thesiscomp > Cresults25.txt
thesiscomp > Cresults26.txt
thesiscomp > Cresults27.txt
thesiscomp > Cresults28.txt
thesiscomp > Cresults29.txt
thesiscomp > Cresults30.txt